version: '3.5'

services:
    nginx:
        image: ${COMPOSE_PROJECT_NAME}-nginx:latest
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        build:
            context: ./docker/
            dockerfile: ./nginx/Dockerfile
        restart: always
        ports:
            - "${WEB_PORT_HTTP}:80"
        volumes:
            - ./:/var/www/html:ro,cached
        depends_on:
            - backend
        networks:
            - backend

    backend: &backend-template
        image: ${COMPOSE_PROJECT_NAME}-backend:latest
        container_name: ${COMPOSE_PROJECT_NAME}-backend
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
        cap_add:
            - SYS_ADMIN
        restart: always
        volumes:
            - .:/var/www/html:cached
        depends_on:
            - mysql
        networks:
            - backend

    supervisord:
        <<: *backend-template
        container_name: supervisord
        expose: [ ]
        command: [ "/usr/bin/supervisord" ]

    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}-mysql
        platform: linux/x86_64
        restart: always
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1}
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "127.0.0.1:33061:3306"
        volumes:
            - ./storage/mysql-data:/var/lib/mysql:delegated
        networks:
            - backend

networks:
    backend:
        name: backend
